name: 'PR Backend'

on:
  pull_request:
    paths:
      - 'backend/**'
jobs:
  check-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - name: checkout
      uses: actions/checkout@master
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: install dependencies
      run: npm install
    - name: run test
      env:
        MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
        MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
        MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
      run: npm run test